### ISSUE TITLE
gem install fails

### ISSUE THREAD

**Issue by patpodenski** [freerange/method_log#1]
Attempting to install method_log results in the following:

ERROR:  While executing gem ... (Gem::DependencyError)
    Unable to resolve dependencies: method_log requires rugged (>= 0), diffy (>= 0), trollop (>= 0)

Tried to install the rugged gem by itself and got:

Temporarily enhancing PATH to include DevKit...
ERROR:  While executing gem ... (Errno::EINVAL)
    Invalid argument - C:/Ruby193/lib/ruby/gems/1.9.1/gems/rugged-0.19.0/test/fixtures/status/h?↓

**Comment by floehopper** [comment]
As explained in my previous comment, this was a problem with the `rugged` gem on Windows, not `method_log` itself. Closing.
